post http://localhost:4000/api/tickets/
Content-Type: application/json

{
    "uniqueUserId" : "52672738-d164-4b24-a458-e94c0ccf9cc4",
    "heureJeu" : "11:20",
    "nomJeu" : "Benin11" ,
    "typeJeu" : "Anagrammes",
    "numerosJoues" : [1,2,2] ,
    "formule" : "Directe",
    "mise" : "10",
    "gains" : "20 (Win) / 60 (Machine)",
    "isCart" : false
}