GET http://localhost:3000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEzLCJpYXQiOjE3NDg3OTIxNzEsImV4cCI6MTc0ODg3ODU3MX0.d_Kd5p3095Rpx5NJGYUSFn7u2O-floylULBmLKlJnNg
Content-Type: application/json

{
  "email": "hello@gmail.com",
  "password": "hello"
}